name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un runner de Ubuntu
    permissions:
      contents: read  # Permiso para leer el repositorio
      packages: write  # Permiso para subir imágenes a GitHub Container Registry
    environment: produccion  # Puedes definir el entorno, por ejemplo, 'produccion'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Obtiene el código del repositorio

      - name: Login on GHCR
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin  # Login al registro de contenedores de GitHub

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/flask-app:latest  # Construye la imagen Docker

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest  # Sube la imagen al registro de contenedores
