name: Build Docker Image

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un runner de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Obtiene el código del repositorio

      - name: Build Docker image
        run: |
          REPO_NAME=$(basename ${{ github.repository }})  # Obtiene el nombre del repositorio
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')  # Convierte el nombre del propietario a minúsculas
          docker build . -t ghcr.io/$OWNER/$REPO_NAME:latest  # Construye la imagen Docker
